name: serena_onlus_login
description: Applicazione di login per pagina web

publish_to: 'Serema Onlus'


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  http: ^0.13.5
  flutter_downloader: ^1.8.4
  permission_handler: ^10.2.0
  url_launcher: ^6.1.6
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.12
  webview_flutter: ^3.0.4
  downloads_path_provider_28: ^0.1.2
  webview_cookie_manager: ^2.0.6

  flutter_local_notifications: ^12.0.3
  dio: ^4.0.6
  flutter_inappwebview: ^5.7.1
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter:
  assets:
    - s.jpg
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/s.jpg"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/s.png"
